apiVersion: v2

name: plexio
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "0.0.1"

dependencies:
  - name: redis
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 17.11.8