steps:
  - name: Build BE
    image: woodpeckerci/plugin-docker-buildx
    settings:
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD
      registry: registry.ivanchenko.io
      repo: registry.ivanchenko.io/${DRONE_REPO_NAME}
      cache_from: registry.ivanchenko.io/${DRONE_REPO_NAME}:main
      tags:
        - ${DRONE_BRANCH/\//-}
        - ${DRONE_BRANCH/\//-}-${DRONE_COMMIT:0:8}
      mtu: 1000

  - name: Build FE
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: frontend/Dockerfile
      context: frontend/
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD
      registry: registry.ivanchenko.io
      repo: registry.ivanchenko.io/${DRONE_REPO_NAME}-frontapp
      cache_from: registry.ivanchenko.io/${DRONE_REPO_NAME}-frontapp:main
      tags:
        - ${DRONE_BRANCH/\//-}
        - ${DRONE_BRANCH/\//-}-${DRONE_COMMIT:0:8}
      mtu: 1000

  - name: helm
    image: alpine/helm:3.10.0
    commands:
      - helm registry login registry.ivanchenko.io -u $${REGISTRY_USERNAME} -p $${REGISTRY_PASSWORD}
      - helm dependency build charts/plexio
      - chart=$$(helm package charts/plexio)
      - helm push $$(basename $${chart#*/}) oci://registry.ivanchenko.io
