app = 'plexio'
primary_region = 'iad'

[build]
  image = 'ghcr.io/sebastianruff/plexio:main'

[env]
  CACHE_TYPE = 'redis'

[http_service]
  internal_port = 80
  force_https = false
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
