apiVersion: v1
kind: Service
metadata:
  name: {{ include "plexio.fullname" . }}-be
  labels:
    app.kubernetes.io/name: {{ include "plexio.name" . }}-be
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "plexio.name" . }}-be
    app.kubernetes.io/instance: {{ .Release.Name }}